###Service
apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  selector:
    app.kubernetes.io/name: backend-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

###App
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: backend-app
spec:
  selector:
    matchLabels:
      app: backend-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: saurabhb0109/springboot-backend-app:latest
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
# The port that the container is running on in the cluster
